# Generated by Django 5.0.4 on 2024-04-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busslogic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
